#!/bin/sh

set -e

# Ensure file names are sorted consistently across platforms.
LC_ALL=C
export LC_ALL

srcdir=`dirname "$0"`
test -z "$srcdir" && srcdir=.
cd "$srcdir"

# Grab Sabaton/Limine
mkdir -p 3rdparty/Sabaton
curl -L https://hub.fastgit.xyz/FlorenceOS/Sabaton/releases/download/rel1/446d75a972abe576ae34994559fb31ce34d634f4.zip > 3rdparty/Sabaton/sb.zip
unzip 3rdparty/Sabaton/sb.zip -d 3rdparty/Sabaton
rm 3rdparty/Sabaton/sb.zip

git clone --depth 1 --branch v3.0-branch-binary https://hub.fastgit.xyz/limine-bootloader/limine 3rdparty/limine
make -C 3rdparty/limine

automake_libdir="$(automake --print-libdir)"
mkdir -p build-aux
cp "${automake_libdir}/install-sh" ./build-aux

autoconf
